name: Bluemetrix Tokenization
description: Tokenize and De-tokenize data
author: Bluemetrix Ltd.
specification_version: 1.0
prototype_version: 1.0
date: "2024-06-14"

runtimes:
  - editor: JupyterLab
    kernel: Python 3.9
    edition: Bluemetrix Tokenization

tasks:
  - type: run_session
    name: Run Tokenization Example
    script: Tokenization_Example.ipynb
    short_summary: Run Tokenization Example
    kernel: python3
    cpu: 2
    memory: 4
